### ISSUE TITLE
Question: Where is BroadcastChannelPubSub used?

### ISSUE THREAD

**Issue by reggi** [floodfx/liveviewjs#110]
The file here with the `BroadcastChannelPubSub` export, where is this used in the deno example?

https://github.com/floodfx/liveviewjs/blob/main/packages/deno/src/deno/broadcastChannelPubSub.ts

**Comment by floodfx** [comment]
Hey @reggi.  Thanks for the question!  It isn't right now.  I'll have to change that...

**Comment by floodfx** [comment]
Added an example LIveView and updated the server to use `BroadcastChannelPubSub`.  Note, any example using `SingleProcessPubSub` (i.e. some of the unlisted LiveView's from the examples package) will not work.  Need to use same `PubSub` type.  

Also note, there is a [known bug](https://github.com/denoland/deno/issues/13214) where you need to add `--unstable` to `deno run` command or you will get an error that looks something like:
```
 ReferenceError: BroadcastChannel is not defined
```
