### ISSUE TITLE
Don't commit built docs

### ISSUE THREAD

**Issue by duffn** [floodfx/liveviewjs#143]
Committing built docs creates huge, very difficult to navigate diffs. https://github.com/floodfx/liveviewjs/pull/95/files. They shouldn't need to be committed in order to be deployed.

**Comment by floodfx** [comment]
Hey thanks @duffn!  I didn't realize they don't need to be committed in order to be deployed.  Will check it out.  and thanks for the PR!

**Comment by duffn** [comment]
👍🏻 It looks like there's some info on GitHub Actions/Pages/Docusaurus here: https://docusaurus.io/docs/deployment#deploying-to-github-pages

**Comment by floodfx** [comment]
resolved with #144 

Thanks again @duffn
