### ISSUE TITLE
Wrong layout in table in markdown docs 

### ISSUE THREAD

**Issue by csarnataro** [floodfx/liveviewjs#145]
This section contains a table with a wrong layout, right after the sentence `help facilitate server events:`

https://www.liveviewjs.com/docs/liveview-socket/liveviewsocket-api-infos#liveviewsocket-properties-and-methods

I will open a PR in a few minutes.

P.S. great project, I'm experimenting with it and I'm having a lot of fun, so far. :)

**Comment by floodfx** [comment]
Really appreciate the PR @csarnataro and glad you re having fun with it!  LMK if you have any other questions or problems.
