### ISSUE TITLE
Support async LiveViewComponentManager methods

### ISSUE THREAD

**Issue by juanpprieto** [floodfx/liveviewjs#31]
Hey Donnie,

First of all, thanks for putting this together. Love it. 

While playing around with the examples (and inspecting the code for the Todo MVC demo), I noticed there are no examples which fetch data externally via async/fetch operations. What's the recommended/planned way of doing so?

I feel as if `mount`, `render`, `handleEvent` and `handleInfo` should all optionally support async signatures, so that one can actually fetch/push data from/to external sources/apis.

I'm new to Liveview (thanks for referencing the pragmatic series), so still trying to wrap my head around some of the more advanced concepts.

Once again, thanks for bringing this to node.

**Comment by floodfx** [comment]
@juanpprieto check out version 0.0.5.  Added an example under `src/examples/asyncfetch`.  LMK what you think.

**Comment by juanpprieto** [comment]
@floodfx Looks great! — will play around with it and keep you posted.

Thanks for the quick turnaround!
