### ISSUE TITLE
Ability to generate a new LiveView project from CLI

### ISSUE THREAD

**Issue by floodfx** [floodfx/liveviewjs#38]
Something like create-react-app...

**Comment by reggi** [comment]
yeah so I've took a deep dive into the files in the deno example, it's all very straight forward and super easy to configure but it's a bit of boiler plate curious how we'd expect people to get started and if there's an easier configuration expierence 🤔 perhaps tucking all these files in a config folder

**Comment by reggi** [comment]
for instance I'd like a version that I wouldn't need to configure at all and run all in one file with deno deploy as a demo

**Comment by floodfx** [comment]
`npx @liveviewjs gen` enabled Node and Deno project template creation.  (doc updates coming)
